### ISSUE TITLE
Integration into existing modules

### ISSUE THREAD

**Issue by abcene** [bishwopl/bpluser#1]
I want to integrate this module in my application with already existing modules but I do not know how to do it. Thanks for help

**Comment by bishwopl** [comment]
I wrote this module to provide features of [zfcuser](https://github.com/ZF-Commons/ZfcUser) and [GoalioForgotPassword](https://github.com/goalio/GoalioForgotPassword) in single module. Configuration file is in [config/bpluser.local.php.dist](https://github.com/bishwopl/bpluser/blob/master/config/bpluser.local.php.dist). Refer to [Saeven/zf3-circlical-user](https://github.com/Saeven/zf3-circlical-user/) to configure gaurds for your controllers and routes because authentication and authorization is done by that module. I will also update readme to make it more elaborate
