### ISSUE TITLE
Fix hasProfileImage entity user

### ISSUE THREAD

**Issue by Iraecio** [bishwopl/bpluser#7]
On cli doctrine 
`"vendor/bin/doctrine-module" orm:schema-tool:update --dump-sql`

`ALTER TABLE users DROP hasProfileImage;`

**Comment by bishwopl** [comment]
This was due to the fact that [User entity](https://github.com/bishwopl/bpluser/blob/master/src/Entity/User.php) did not have `hasProfileImage` property but user table in [schema_sql.sql](https://github.com/bishwopl/bpluser/blob/master/schema_sql.sql) had `hasProfileImage` column.  I have updated [schema_sql.sql](https://github.com/bishwopl/bpluser/blob/master/schema_sql.sql) file.
